//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("arjajobsModel", "FK_IMAGE_ID_USER", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PWMM.Models.DB.Users), "Image", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PWMM.Models.DB.Image), true)]

#endregion

namespace PWMM.Models.DB
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class arjajobsEntities4 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new arjajobsEntities4 object using the connection string found in the 'arjajobsEntities4' section of the application configuration file.
        /// </summary>
        public arjajobsEntities4() : base("name=arjajobsEntities4", "arjajobsEntities4")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new arjajobsEntities4 object.
        /// </summary>
        public arjajobsEntities4(string connectionString) : base(connectionString, "arjajobsEntities4")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new arjajobsEntities4 object.
        /// </summary>
        public arjajobsEntities4(EntityConnection connection) : base(connection, "arjajobsEntities4")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Image> Image
        {
            get
            {
                if ((_Image == null))
                {
                    _Image = base.CreateObjectSet<Image>("Image");
                }
                return _Image;
            }
        }
        private ObjectSet<Image> _Image;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Users> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<Users>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<Users> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Image EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToImage(Image image)
        {
            base.AddObject("Image", image);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="arjajobsModel", Name="Image")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Image : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Image object.
        /// </summary>
        /// <param name="iD_IMAGE">Initial value of the ID_IMAGE property.</param>
        /// <param name="iD_USER">Initial value of the ID_USER property.</param>
        /// <param name="sOURCE">Initial value of the SOURCE property.</param>
        public static Image CreateImage(global::System.Int32 iD_IMAGE, global::System.Int32 iD_USER, global::System.String sOURCE)
        {
            Image image = new Image();
            image.ID_IMAGE = iD_IMAGE;
            image.ID_USER = iD_USER;
            image.SOURCE = sOURCE;
            return image;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_IMAGE
        {
            get
            {
                return _ID_IMAGE;
            }
            set
            {
                if (_ID_IMAGE != value)
                {
                    OnID_IMAGEChanging(value);
                    ReportPropertyChanging("ID_IMAGE");
                    _ID_IMAGE = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_IMAGE");
                    OnID_IMAGEChanged();
                }
            }
        }
        private global::System.Int32 _ID_IMAGE;
        partial void OnID_IMAGEChanging(global::System.Int32 value);
        partial void OnID_IMAGEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_USER
        {
            get
            {
                return _ID_USER;
            }
            set
            {
                OnID_USERChanging(value);
                ReportPropertyChanging("ID_USER");
                _ID_USER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_USER");
                OnID_USERChanged();
            }
        }
        private global::System.Int32 _ID_USER;
        partial void OnID_USERChanging(global::System.Int32 value);
        partial void OnID_USERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TITLE
        {
            get
            {
                return _TITLE;
            }
            set
            {
                OnTITLEChanging(value);
                ReportPropertyChanging("TITLE");
                _TITLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TITLE");
                OnTITLEChanged();
            }
        }
        private global::System.String _TITLE;
        partial void OnTITLEChanging(global::System.String value);
        partial void OnTITLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TITLE2
        {
            get
            {
                return _TITLE2;
            }
            set
            {
                OnTITLE2Changing(value);
                ReportPropertyChanging("TITLE2");
                _TITLE2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TITLE2");
                OnTITLE2Changed();
            }
        }
        private global::System.String _TITLE2;
        partial void OnTITLE2Changing(global::System.String value);
        partial void OnTITLE2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IMAGE1
        {
            get
            {
                return _IMAGE1;
            }
            set
            {
                OnIMAGE1Changing(value);
                ReportPropertyChanging("IMAGE1");
                _IMAGE1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IMAGE1");
                OnIMAGE1Changed();
            }
        }
        private global::System.String _IMAGE1;
        partial void OnIMAGE1Changing(global::System.String value);
        partial void OnIMAGE1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SOURCE
        {
            get
            {
                return _SOURCE;
            }
            set
            {
                OnSOURCEChanging(value);
                ReportPropertyChanging("SOURCE");
                _SOURCE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SOURCE");
                OnSOURCEChanged();
            }
        }
        private global::System.String _SOURCE;
        partial void OnSOURCEChanging(global::System.String value);
        partial void OnSOURCEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PLUS
        {
            get
            {
                return _PLUS;
            }
            set
            {
                OnPLUSChanging(value);
                ReportPropertyChanging("PLUS");
                _PLUS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PLUS");
                OnPLUSChanged();
            }
        }
        private Nullable<global::System.Int32> _PLUS;
        partial void OnPLUSChanging(Nullable<global::System.Int32> value);
        partial void OnPLUSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MINUS
        {
            get
            {
                return _MINUS;
            }
            set
            {
                OnMINUSChanging(value);
                ReportPropertyChanging("MINUS");
                _MINUS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MINUS");
                OnMINUSChanged();
            }
        }
        private Nullable<global::System.Int32> _MINUS;
        partial void OnMINUSChanging(Nullable<global::System.Int32> value);
        partial void OnMINUSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATE
        {
            get
            {
                return _DATE;
            }
            set
            {
                OnDATEChanging(value);
                ReportPropertyChanging("DATE");
                _DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATE");
                OnDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATE;
        partial void OnDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnDATEChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("arjajobsModel", "FK_IMAGE_ID_USER", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("arjajobsModel.FK_IMAGE_ID_USER", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("arjajobsModel.FK_IMAGE_ID_USER", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("arjajobsModel.FK_IMAGE_ID_USER", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("arjajobsModel.FK_IMAGE_ID_USER", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="arjajobsModel", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="iD_USER">Initial value of the ID_USER property.</param>
        public static Users CreateUsers(global::System.Int32 iD_USER)
        {
            Users users = new Users();
            users.ID_USER = iD_USER;
            return users;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_USER
        {
            get
            {
                return _ID_USER;
            }
            set
            {
                if (_ID_USER != value)
                {
                    OnID_USERChanging(value);
                    ReportPropertyChanging("ID_USER");
                    _ID_USER = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_USER");
                    OnID_USERChanged();
                }
            }
        }
        private global::System.Int32 _ID_USER;
        partial void OnID_USERChanging(global::System.Int32 value);
        partial void OnID_USERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LOGIN
        {
            get
            {
                return _LOGIN;
            }
            set
            {
                OnLOGINChanging(value);
                ReportPropertyChanging("LOGIN");
                _LOGIN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LOGIN");
                OnLOGINChanged();
            }
        }
        private global::System.String _LOGIN;
        partial void OnLOGINChanging(global::System.String value);
        partial void OnLOGINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PASS
        {
            get
            {
                return _PASS;
            }
            set
            {
                OnPASSChanging(value);
                ReportPropertyChanging("PASS");
                _PASS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PASS");
                OnPASSChanged();
            }
        }
        private global::System.String _PASS;
        partial void OnPASSChanging(global::System.String value);
        partial void OnPASSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RULES
        {
            get
            {
                return _RULES;
            }
            set
            {
                OnRULESChanging(value);
                ReportPropertyChanging("RULES");
                _RULES = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RULES");
                OnRULESChanged();
            }
        }
        private Nullable<global::System.Int32> _RULES;
        partial void OnRULESChanging(Nullable<global::System.Int32> value);
        partial void OnRULESChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("arjajobsModel", "FK_IMAGE_ID_USER", "Image")]
        public EntityCollection<Image> Image
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Image>("arjajobsModel.FK_IMAGE_ID_USER", "Image");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Image>("arjajobsModel.FK_IMAGE_ID_USER", "Image", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
