//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace PWMM.Models.DB
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class arjajobsEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new arjajobsEntities1 object using the connection string found in the 'arjajobsEntities1' section of the application configuration file.
        /// </summary>
        public arjajobsEntities1() : base("name=arjajobsEntities1", "arjajobsEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new arjajobsEntities1 object.
        /// </summary>
        public arjajobsEntities1(string connectionString) : base(connectionString, "arjajobsEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new arjajobsEntities1 object.
        /// </summary>
        public arjajobsEntities1(EntityConnection connection) : base(connection, "arjajobsEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Profil> Profil
        {
            get
            {
                if ((_Profil == null))
                {
                    _Profil = base.CreateObjectSet<Profil>("Profil");
                }
                return _Profil;
            }
        }
        private ObjectSet<Profil> _Profil;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Image> Image
        {
            get
            {
                if ((_Image == null))
                {
                    _Image = base.CreateObjectSet<Image>("Image");
                }
                return _Image;
            }
        }
        private ObjectSet<Image> _Image;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Profil EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProfil(Profil profil)
        {
            base.AddObject("Profil", profil);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Image EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToImage(Image image)
        {
            base.AddObject("Image", image);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="arjajobsModel", Name="Image")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Image : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Image object.
        /// </summary>
        /// <param name="uSER_ID">Initial value of the USER_ID property.</param>
        /// <param name="sOURCE">Initial value of the SOURCE property.</param>
        public static Image CreateImage(global::System.Int32 uSER_ID, global::System.String sOURCE)
        {
            Image image = new Image();
            image.USER_ID = uSER_ID;
            image.SOURCE = sOURCE;
            return image;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ID_IMAGE
        {
            get
            {
                return _ID_IMAGE;
            }
            set
            {
                OnID_IMAGEChanging(value);
                ReportPropertyChanging("ID_IMAGE");
                _ID_IMAGE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ID_IMAGE");
                OnID_IMAGEChanged();
            }
        }
        private global::System.String _ID_IMAGE;
        partial void OnID_IMAGEChanging(global::System.String value);
        partial void OnID_IMAGEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 USER_ID
        {
            get
            {
                return _USER_ID;
            }
            set
            {
                if (_USER_ID != value)
                {
                    OnUSER_IDChanging(value);
                    ReportPropertyChanging("USER_ID");
                    _USER_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("USER_ID");
                    OnUSER_IDChanged();
                }
            }
        }
        private global::System.Int32 _USER_ID;
        partial void OnUSER_IDChanging(global::System.Int32 value);
        partial void OnUSER_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TITLE
        {
            get
            {
                return _TITLE;
            }
            set
            {
                OnTITLEChanging(value);
                ReportPropertyChanging("TITLE");
                _TITLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TITLE");
                OnTITLEChanged();
            }
        }
        private global::System.String _TITLE;
        partial void OnTITLEChanging(global::System.String value);
        partial void OnTITLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TITLE2
        {
            get
            {
                return _TITLE2;
            }
            set
            {
                OnTITLE2Changing(value);
                ReportPropertyChanging("TITLE2");
                _TITLE2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TITLE2");
                OnTITLE2Changed();
            }
        }
        private global::System.String _TITLE2;
        partial void OnTITLE2Changing(global::System.String value);
        partial void OnTITLE2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IMAGE1
        {
            get
            {
                return _IMAGE1;
            }
            set
            {
                OnIMAGE1Changing(value);
                ReportPropertyChanging("IMAGE1");
                _IMAGE1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IMAGE1");
                OnIMAGE1Changed();
            }
        }
        private global::System.String _IMAGE1;
        partial void OnIMAGE1Changing(global::System.String value);
        partial void OnIMAGE1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SOURCE
        {
            get
            {
                return _SOURCE;
            }
            set
            {
                if (_SOURCE != value)
                {
                    OnSOURCEChanging(value);
                    ReportPropertyChanging("SOURCE");
                    _SOURCE = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SOURCE");
                    OnSOURCEChanged();
                }
            }
        }
        private global::System.String _SOURCE;
        partial void OnSOURCEChanging(global::System.String value);
        partial void OnSOURCEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PLUS
        {
            get
            {
                return _PLUS;
            }
            set
            {
                OnPLUSChanging(value);
                ReportPropertyChanging("PLUS");
                _PLUS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PLUS");
                OnPLUSChanged();
            }
        }
        private Nullable<global::System.Int32> _PLUS;
        partial void OnPLUSChanging(Nullable<global::System.Int32> value);
        partial void OnPLUSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MINUS
        {
            get
            {
                return _MINUS;
            }
            set
            {
                OnMINUSChanging(value);
                ReportPropertyChanging("MINUS");
                _MINUS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MINUS");
                OnMINUSChanged();
            }
        }
        private Nullable<global::System.Int32> _MINUS;
        partial void OnMINUSChanging(Nullable<global::System.Int32> value);
        partial void OnMINUSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATE
        {
            get
            {
                return _DATE;
            }
            set
            {
                OnDATEChanging(value);
                ReportPropertyChanging("DATE");
                _DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATE");
                OnDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATE;
        partial void OnDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnDATEChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="arjajobsModel", Name="Profil")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Profil : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Profil object.
        /// </summary>
        /// <param name="iD_USER">Initial value of the ID_USER property.</param>
        public static Profil CreateProfil(global::System.Int32 iD_USER)
        {
            Profil profil = new Profil();
            profil.ID_USER = iD_USER;
            return profil;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_USER
        {
            get
            {
                return _ID_USER;
            }
            set
            {
                if (_ID_USER != value)
                {
                    OnID_USERChanging(value);
                    ReportPropertyChanging("ID_USER");
                    _ID_USER = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_USER");
                    OnID_USERChanged();
                }
            }
        }
        private global::System.Int32 _ID_USER;
        partial void OnID_USERChanging(global::System.Int32 value);
        partial void OnID_USERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LOGIN
        {
            get
            {
                return _LOGIN;
            }
            set
            {
                OnLOGINChanging(value);
                ReportPropertyChanging("LOGIN");
                _LOGIN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LOGIN");
                OnLOGINChanged();
            }
        }
        private global::System.String _LOGIN;
        partial void OnLOGINChanging(global::System.String value);
        partial void OnLOGINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PASS
        {
            get
            {
                return _PASS;
            }
            set
            {
                OnPASSChanging(value);
                ReportPropertyChanging("PASS");
                _PASS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PASS");
                OnPASSChanged();
            }
        }
        private global::System.String _PASS;
        partial void OnPASSChanging(global::System.String value);
        partial void OnPASSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RULES
        {
            get
            {
                return _RULES;
            }
            set
            {
                OnRULESChanging(value);
                ReportPropertyChanging("RULES");
                _RULES = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RULES");
                OnRULESChanged();
            }
        }
        private Nullable<global::System.Int32> _RULES;
        partial void OnRULESChanging(Nullable<global::System.Int32> value);
        partial void OnRULESChanged();

        #endregion
    
    }

    #endregion
    
}
